### ISSUE TITLE
Differentiate between drag and click events

### ISSUE THREAD

**Issue by maxcodefaster2** [blaze-slider/blaze-slider#16] opened 2022-10-25 08:21 UTC
Currently you can not reliably add add a click event to the slides as it detects it as a grab event. You should be able to differentiate between click and grab by calculating the delta: https://stackoverflow.com/a/59741870

**Comment by MananTank** [comment] 2022-10-25 08:38
Can you clarify what exactly you are trying to do?

**Comment by maxcodefaster2** [comment] 2022-10-25 08:58
I have a slider of clickable divs / cards. The onclick event of these is not being triggered, cause the slider overrides it with its drag events. To differentiate between drags and clicks it would be useful if your drag.ts file checks for a delta for triggering the drag (see https://stackoverflow.com/a/59741870 )

**Comment by MananTank** [comment] 2022-10-25 09:02
@maxcodefaster2 Thanks for the details, I will test this out and fix it ASAP

**Comment by maxcodefaster2** [comment] 2022-10-25 09:04
@MananTank thank you! I just checked and even if i have child elements in the blaze-track elments, lets say a button in a div, the onclick is not triggered reliably.

**Comment by MananTank** [comment] 2022-10-25 09:24
It looks like the root cause here is that using setPointerCapture is disabling the click events as mentioned here: https://github.com/GoogleChromeLabs/pointer-tracker/issues/4

This solution looks good and works well: https://github.com/GoogleChromeLabs/pointer-tracker/issues/4#issuecomment-593936162

**Comment by maxcodefaster2** [comment] 2022-10-25 09:45
Nice! eagerly waiting for new release :)

**Comment by MananTank** [comment] 2022-10-25 10:00
@maxcodefaster2 v1.7.0 is released with this fix. 
Check it out: https://codesandbox.io/s/blaze-slider-playground-click-fixed-1ptrrf?file=/index.html

**Comment by MananTank** [comment] 2022-10-25 10:05
@maxcodefaster2 Thanks for creating this issue - It was a major bug that I did know existed. Appreciate it! 🙌

**Closed** 2022-10-25 10:04 UTC
Labels: bug, high-priority
